# Config file for Air
[build]
# Command to build the app
cmd = "go build -o main cmd/main.go"
# Binary to watch
bin = "main"
# Working directory
dire = "."
# Patterns to watch
include_ext = ["go"]
# Exclude files
exclude_dir = ["vendor"]
# Command to run after build
run_after_build = "chmod +x main"

exclude_unchanged = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
level = "debug"
