version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: linktly_pg_db
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - dbdata:/data/db
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

volumes:
  dbdata:
