version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - ./configs/.env
    depends_on:
      - postgres
  postgres:
    image: jegj/postgres_16_uuidv7
    container_name: linktly_pg_db
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - dbdata:/data/db
    env_file:
      - ./configs/.env
volumes:
  dbdata:
