services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linktly_web
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - ./configs/.env
    environment:
      DBHOST: postgres
      DBPORT: 5432
    depends_on:
      - postgres
  postgres:
    image: jegj/postgres_16_uuidv7
    container_name: linktly_pg_db
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - dbdata:/data/db
    env_file:
      - ./configs/.env
volumes:
  dbdata:
